# Generated by Django 5.2.6 on 2026-01-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='accounts.account'),
            preserve_default=False,
        ),
    ]
